### ISSUE TITLE
隐写者恶性bug

### ISSUE THREAD

**Issue by zhangerdong20030514** [cenglin123/SteganographierGUI#3]
作者你好，我是smallears，我在仓库https://cangku.moe/archives/208981 页面发现了您的投稿 https://pan.baidu.com/share/init?surl=x0FuR2LIomZYzJ-PcZY2rQ ，您的隐写文件在下载后会出现严重的恶性bug，这是bug的录屏和图片的分享：通过百度网盘分享的文件：隐写者文件录屏
链接：https://pan.baidu.com/s/1DSc-PcLbK5QUUmZSMCz6ew?pwd=vr3s 
提取码：vr3s 
--来自百度网盘超级会员V7的分享，
具体触发流程及表现形式如下：
一旦进入下载了包含隐写文件的文件夹就会触发，表现为文件管理器绿条无限加载，文件重命名会导致文件管理器卡死，cmd重命名无效，文件无法删除等，使用火绒文件粉碎结果仍然是粉碎失败，（不是哥们，文件粉碎都拿它没办法，比一般病毒nb），即使不进行任何操作，如果不及时退出包含隐写文件的文件夹，explorer最终会卡死重启而不是完成加载
如果想完全删除问题文件，我目前的方法是反复重启，每一次重启都能删除一部分（如分享图片里所示）
我确信作者绝不会传播计算机病毒，但这些表现与病毒几乎一摸一样，我不知道具体触发的细节和原因，希望作者早日修复（如果电脑小白遇到了，估计就以为中毒了）
如果需要我提供其他信息，请留言

**Comment by cenglin123** [comment]
你好，我这边无法复现你的bug，能不能给出你所用的隐写者版本以及你的系统配置？
https://pan.baidu.com/s/1QT7EnozdeDwBWUxhAzQiWA?pwd=6666

**Comment by zhangerdong20030514** [comment]
经校验，hash与视频中的完全相同
![image](https://github.com/user-attachments/assets/dde4015c-040d-480a-840b-8602ec53991a)

**Comment by cenglin123** [comment]
我的意思是，你自己有尝试本地隐写一个文件然后解压吗？这种情况会不会出问题？如果会出问题，把那个文件发给我看看

**Comment by cenglin123** [comment]
我看了一下你的报告，你把这个程序先停一下 `TransparentTaskbar.exe` 
然后把这项取消选择
![Clip_2024-08-13_21-39-59](https://github.com/user-attachments/assets/afb60250-856e-4d95-9b12-04d68fcfb6fb)

看看有没有影响？

**Comment by zhangerdong20030514** [comment]
https://1drv.ms/f/c/88c7bc5e89896c06/EsNQ6zmXXYNKse2xuCjamjEB8Tf6WEIghnxRsAnckcdXAw?e=uYNZGL
关闭箭头所示设置的视频 问题仍会出现
这是我的隐写文件和 隐写文件使用的是1.2.0.1版本的隐写者 我创建的隐写文件也会有一样的问题
transparent taskbar这个软件从第一次出问题的时候开始就没启动过
![image](https://github.com/user-attachments/assets/4c86dc44-8ba6-4d95-99d1-cf02ce7bad72)
![image](https://github.com/user-attachments/assets/c5297cce-f88e-4235-b704-a7a518df6f1c)

**Comment by cenglin123** [comment]
我们来排查一下问题，把这 4 个文件逐个放进单独的文件夹然后打开文件夹，哪些文件在你那边会出问题？
https://pan.baidu.com/s/1B6N-rbN0CnHMn02YaIFgGw?pwd=6666
![Clip_2024-08-14_10-15-09](https://github.com/user-attachments/assets/7eae5d44-2f99-4966-9b94-68d8c1a42eda)

**Comment by cenglin123** [comment]
然后，如果上述都有问题，那么再测试一下 5、6 号文件的情况
![Clip_2024-08-14_10-41-30](https://github.com/user-attachments/assets/000cd225-e0f2-4a00-8849-e2287e3612fd)

**Comment by zhangerdong20030514** [comment]
你好，我现在没有时间，晚些时候给你答复

**Comment by zhangerdong20030514** [comment]
作者你好，在下载时就将文件单独下载到对应的文件夹，依次打开对应的文件夹，其中2,4号文件所在的文件夹在打开时完全正常，其余的文件在单独打开时管理器均会出现无限加载的情况，无法被移动，也无法被删除

**Comment by zhangerdong20030514** [comment]
2024-08-14 09-30-50.mp4这个文件下载下来直接就会出现无限读条的问题，无法移动或删除 命令可以执行并输出结果 但输出的output文件同样无法移动，无法删除

**Comment by cenglin123** [comment]
如果是这样，那就不是隐写者的问题，因为这个视频就是你之前发的原视频用ffmpeg 转换为hevc编码mp4的结果，你可以直接在百度网盘中播放。
假如hevc编码mp4文件在你的设备上会出问题，那么隐写者cover_video 文件夹中自带的 Never gonna give you up.mp4 等视频文件也会出问题。
或者你可以安装一个potplayer 试试

**Comment by zhangerdong20030514** [comment]
在出现bug时使用火绒解除文件占用这个功能得出是“dllhost”这个文件占用了隐写文件导致bug出现 解决方案参考https://answers.microsoft.com/zh-hans/windows/forum/all/%E5%85%B3%E4%BA%8Ewindows-10/fb80635a-3848-4ab5-a4df-1a04196d9bba
应该是windows的历史遗留问题 这不怪隐写者

**Comment by zhangerdong20030514** [comment]
谢谢 如果没有其他问题 我会在24小时后关闭对话 再见

**Comment by cenglin123** [comment]
行，我这边把issue关了，有新问题提新的issue
