### ISSUE TITLE
解隐时有个不影响使用的小问题

### ISSUE THREAD

**Issue by x0phi** [cenglin123/SteganographierGUI#4]
当前使用 v1.2.1 的 GUI 界面，对内含隐藏内容的文件进行解隐时：
如果文件本身没有设置密码，此时左上角的“密码”框留空不填，那么软件是无法正常执行解隐恢复操作的，只会提示你尝试了所有密码失败无法解压。
要让软件正常执行解隐，此时必须在左上角"密码"框填入一个空格，软件才能正常识别成该文件未设密码，进而成功执行解隐恢复的操作。
所以当前对于未设密码的文件要进行解隐恢复的话，必须要在左上密码框填一个空格才行，虽然不影响操作，但确实有这么个小问题

**Comment by cenglin123** [comment]
已经在 1.2.4 版本中修复此问题

**Comment by x0phi** [comment]
哦！效率高呀，感谢工具分享
